### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by christian-heusel** [p08dev/keycloak-hcaptcha#4]
Hey, any chance this is getting a new release any time soon?

I [packaged this](https://archlinux.org/packages/extra/any/keycloak-hcaptcha/) for Archlinux yesterday to fight the spam we are getting in our gitlab instance (via keycloak) and the package currently builds off the `master` branch.

**Comment by p08dev** [comment]
Thanks to @mwllgr there is a new [release](https://github.com/p08dev/keycloak-hcaptcha/releases/tag/v1.0.1)
