### ISSUE TITLE
X-FRAME-OPTIONS shouldn't be needed

### ISSUE THREAD

**Issue by hb0** [p08dev/keycloak-hcaptcha#7]
Only adding hcaptcha.com to `Content-Security-Policy > frame-src` should be enough to allow hCaptcha being loaded inside an iframe.

From my understanding, adding hcaptcha.com to `X-Frame-Options` allows hcaptcha.com to load YOUR Keycloak page in their website inside an iframe. (X-Frame-Options as a fall-back for `frame-ancestors` in very old browsers)

[See Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options):

> Sites can use this [X-Frame-Options] [...] ensuring that _their_ content is not embedded into _other_ sites.

**Comment by p08dev** [comment]
You're right. I changed it in the readme! :)
